version: '3.3'
services:
  db:
    image: mysql:8.0
    volumes:
      - db_vol:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: petclinic
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
    ports:
      - 3306:3306
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: petclinic
  web:
    depends_on:
      - db
    image: karldocker25/tomcat:9.0.46
    volumes:
      - ./target/petclinic.war:/usr/local/tomcat/webapps/petclinic.war
    ports:
      - '8080:8080'
    environment:
      MYSQL_ROOT_PASSWORD: petclinic
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
volumes:
  db_vol:
