version: '3.3'
services:
  web:
    image: tomcat:9.0.46
    volumes:
      - ./target/petclinic.war:/usr/local/tomcat/webapps/petclinic.war
    ports:
      - '8080:8080'
    environment:
      MYSQL_ROOT_PASSWORD: petclinic
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic